ghen an error occurs within a method, the method creates an object and hands it off to the runtime system.
The object, called an exception object, contains information about the error,
including its type and the state of the program when the error occurred.
Creating an exception object and handing it to the runtime system is called throwing an exception.

After a method throws an exception, the runtime system attempts to find something to handle it.
The set of possible "somethings" to handle the exception is the ordered list of methods
that had been called to get to the method where the error occurred.
The list of methods is known as the call stack (see the next figure).